### ISSUE TITLE
Keyboard backlights can't be turned off

### ISSUE THREAD

**Issue by Gigadoc2** [RPigott/blight#1]
Hi and thanks for the tool!

I have one minor nitpick, and that is that the line
https://github.com/RPigott/blight/blob/154ae0baeadeb24605e0e6d43bb00c7c9fee8e52/blight.py#L65
seems to also affect the keyboard backlighting, so blight can't be used to turn off the keyboard backlights.

On a side note, where do these values come from? On my W530 I do have a brightness level way over 100, but 0 is still a valid level (and does not turn off my screen either).

**Comment by rpigott** [comment]
Hey @Gigadoc2, glad you like it.

And yeah that could probably be changed. I guess it should probably only care about a minimum value for backlight devices, not leds.

> where do these values come from? 

I stole them from GNOME: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/power/gsd-backlight.c#L237. It's kinda hard to come up with good defaults on your own since there doesn't appear to be any common convention between devices on the meaning of the raw brightness values.

**Comment by Gigadoc2** [comment]
I see, yes the situation is somewhat problematic :D
While I don't know about other hardware, on mine 0 and 1 make no real visual difference, so I am fine either way :)

BTW, I just realized that my keyboard backlight has a `max_brightness` of 2, so it seems that it is not of type `raw` then?

EDIT: It, uh, has no type. At least, `get_sysfs_attr("type")` does not return anything, and there is no sysfs node 'type' next to it either.

**Comment by rpigott** [comment]
Yeah the type only matters for backlight devices, not leds.
